name: decision-transformer-gym
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.8
  - numpy=1.20.3
  - pip<24.1
  - setuptools<60
  - wheel<0.38

  - pytorch=2.1.2
  - pytorch-cuda=11.8


  - pip:
      - gym==0.18.3
      - mujoco-py==2.1.2.14
      - transformers==4.5.1
      - tokenizers==0.10.3
      - packaging==20.9
      - wandb==0.9.1
      - "Cython<3"
      - "pillow<9.0"
      - six
      - git+https://github.com/rail-berkeley/d4rl@master
